# Generated by Django 5.2.17 on 2026-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_slug",
                    models.CharField(
                        choices=[
                            ("akagera-game-lodge", "Akagera Game Lodge"),
                            ("epca-group-headquarters", "EPCA Group Headquarters"),
                            (
                                "keya-nkora-cyimbili-hpp",
                                "Keya, Nkora & Cyimbili HPP Works",
                            ),
                            ("kanombe-warehouses", "Kanombe Warehouses"),
                            ("karongi-quay", "Karongi Auxiliary Quay"),
                            ("lebanon-hotel", "Lebanon Hotel (3 Star)"),
                            ("luxury-apartments", "Luxury Apartments - Kagarama"),
                            (
                                "residential-house-kimihurura",
                                "Residential House - Kimihurura",
                            ),
                            ("rubavu-port", "Port of Rubavu"),
                            ("rusizi-port", "Rusizi Port"),
                            (
                                "shango-birembo-transmission",
                                "220kV Shango-Birembo Transmission Line",
                            ),
                            ("trinity-school", "Trinity International School"),
                        ],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
